name: Nyan
description: Nyan plugin
version: 0.0.1
author: def750
website: https://seventwentyseven.xyz

main: xyz.seventwentyseven.nyan.Main
api-version: "1.20"

load: STARTUP
folia-supported: false

commands:
  nyan:
    description: Nyan command
    usage: /<command>
    aliases: [nyan]

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:2.0.0-Beta2
