name: Nyan
version: '${version}'
main: xyz.seventwentyseven.nyan.Nyan
api-version: '1.20'
author: def750
website: https://seventwentyseven.xyz
description: Nyan :333
commands:
  nyan:
    description: Nyan :333
